config/routes.rb
Treegeek::Application.routes.draw do
  
  resources :trees do
    resources :photos
    collection do
      get "search"
    end
  end

  resources :blogs

  
  resources :kinds do
    collection do
      get 'search'
    end
    member do
      get  'images'
    end
  end
  
  resources :pictures do
    member do
      put 'assignedtrees'
    end
    collection do
      post 'selected_trees'
      get 'search'
    end
  end
  
  
  resources :albums

  

end

app/models/kind.rb
 class Kind
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::Search

  paginates_per 20

  validates_uniqueness_of :botanic_name
  
  field :family, :type => String
  field :botanic_name, :type => String, :required => true
  field :english_name, :type => String
  field :maori_name, :type => String
  field :description, :type => String
  field :icon, :type => Fixnum

  references_one :tree

  
  # From mongoid_search gem
  # search creates an array of stemmed tags in each instance of a Kind, for keyword searching
  # plus provides a search method
  search_in :botanic_name, :english_name, :maori_name

  
  # Set the default page limit for kinds.
  def self.page_limit
    15
  end
  
  # 
  # Note that this replaces Pictures entirely with the non "0" keys.
  # Will need refactoring when dealing with large number of images (or multi-submits)
  #     
  def add_images(selection)    
      #@pictures = [selection.delete_if {|k, v| v == "0"}.keys, @pictures].flatten.compact.uniq
      @pictures = selection.delete_if {|k, v| v == "0"}.keys
      #Rails.logger.info(">>>Picture after add: #{self.pictures.inspect}")
  end
  
  
  def get_one_image_random
    # Sample picks one of the elements from the array for display.  If there is no image, return nil
    self.pictures != nil ? Pictureandmeta.find({:id => self.pictures.sample.to_i}) : nil
  end

  def get_icon
    # Gets the icon image
    #@icon.blank? ? nil : Pictureandmeta.find({:id => @icon.to_i})
    #Rails.logger.info(">>>Get Icon: #{self.inspect}, Botanic: #{self.botanic_name}, ICON: #{self.icon}")
    Pictureandmeta.find({:id => self.icon})
  end
  
  def image_checked?(pic_id)
    # determine if the picture id supplied is checked in the kind
    #Rails.logger.info(">>>Image_Checked: #{pictures.inspect}, #{pic_id}")
    if self.pictures != nil
      self.pictures.find {|p| p == pic_id } != nil ? true : false
    else
      false
    end
  end
  
end

app/controllers/kinds_controller.rb
class KindsController < ApplicationController

  uses_tiny_mce

  def index
    #
    # GET /kinds
    #params[:page].nil? ? @page = 1 : @page = params[:page].to_i
    #@kinds = Kind.all.paginate(:page => @page, :per_page => Kind.page_limit)

    @kinds = Kind.all.page params[:page]

    respond_to do |format|
      format.html
      format.xml {render :xml => @kinds}
    end
    
  end
  
  def show
    #
    # GET kind
    # 
    @kind = Kind.find(params[:id])
  end
  
  def new
    #
    @kind = Kind.new
  end
  
  def create
    #
    # POST kinds
    #
    @kind = Kind.new(params[:kind])
    if @kind.save
      flash[:notice] = "Successfully created kind."
      redirect_to @kind
    else
      render :action => 'new'
    end
  end
  
  def edit
    @kind = Kind.find(params[:id])
  end
  
  def update
    #
    # PUTS Kind
    #
    @kind = Kind.find(params[:id])
    respond_to do |format|
      if @kind.update_attributes(params[:kind])
        flash[:notice] = "Successfully updated kind."
        format.html {redirect_to @kind}
        format.xml {head :ok }
      else
        format.html { render :action => 'edit' }
        format.xml { render :xml => @kind.errors, :status => :unprocessable_entity}
      end  
    end
    
  end
  
  def destroy
    #
    # DELETE Kind
    #
    @kind = Kind.find(params[:id])
    @kind.destroy
    flash[:notice] = "Successfully destroyed kind."
    redirect_to kinds_url
  end

  # Member route methods here

  def images
    @picturesandmeta = Pictureandmeta.all
    @kind = Kind.find(params[:kind_id])
    Rails.logger.info("Kind: #{@kind.inspect}")
  end

  # Collection Route methods here

  # This is basically an algorithm resource GET kinds/search
  def search
    # if the user has selected to clear the search, or there is no search params, start from the top
    if params[:clear] || params[:q] == ""
      Rails.logger.info("Kind: #{params.inspect}")
      redirect_to kinds_path
    else  
      @kinds = Kind.search(params[:q]).page params[:page]
      #@page = 1
      render :index
    end
  end

end

app/helpers/kinds_helper.rb
module KindsHelper
  def imageref(kind_name)
    image_tag (kind_name + ".jpg")
  end

  def page_for
  	text_field_tag :page, @page
  end

end

app/views/kinds/_form.html.erb
<%= form_for @kind do |f| %>

<%= render "shared/error_messages", :target => @kind %>

  <p>
    <%= f.label :botanic_name %><br />
    <%= f.text_field :botanic_name %>
  </p>
  <p>
    <%= f.label :english_name %><br />
    <%= f.text_field :english_name %>
  </p>
  <p>
    <%= f.label :maori_name %><br />
    <%= f.text_field :maori_name %>
  </p>
    <p>
    <%= f.label :family %><br />
    <%= f.text_field :family %>
  </p>
  <p>
    <%= f.label :description %><br />
    <%= f.text_area :description, :class => "mceEditor" %>
  </p>
  <p>
    <%= f.label :icon %>
    <%= f.select(:icon, Pictureandmeta.all.map{|p| [p.meta.name, p.picture.id]}, {:include_blank => true} ) %>
  </p>  
  <p><%= f.submit "Submit" %></p>

<% end %>

app/views/kinds/edit.html.erb
<% title "Edit Kind" %>

<%= render :partial => 'form' %>

<p>
  <%= link_to "Show", @kind %> |
  <%= link_to "View All", kinds_path %>
</p>

app/views/kinds/index.html.erb
<% title "Kinds" %>

<%= form_tag search_kinds_path, :method => :get do %>
  <p>
    <%= text_field_tag :q, params[:q] %>
    <%= submit_tag "Search", :name => "search" %>
    <%= submit_tag "Clear", :name => "clear" %>
  </p>
<% end %>

<table>
  <tr>
	<th>Tree Thumb</th>
	<th>Botanic Name</th>
  </tr>
  <% for kind in @kinds %>
    <tr>
    <td><%= image_tag kind.get_icon.picture.image.url(:thumb) unless kind.icon.blank? %> </td>
	  <td><%=h kind.botanic_name %></td>
      <td><%= link_to "Show", kind %></td>
      <td><%= link_to "Edit", edit_kind_path(kind) %></td>
      <td><%= link_to "Destroy", kind, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p>Per Page <%= "#{@kinds.per_page}, #{@kinds.count}" %> </p>

<%= paginate @kinds %>

<p><%= link_to "New Kind", new_kind_path %></p>

app/views/kinds/new.html.erb
<% title "New Kind" %>

<%= render :partial => 'form' %>

<p><%= link_to "Back to List", kinds_path %></p>

app/views/kinds/show.html.erb
<% title "Kind", @kind.botanic_name %>

<p>
  <strong>Botanic Name:</strong>
  <%=h @kind.botanic_name %>
</p>
<p>
  <strong>Maori Name:</strong>
  <%=h @kind.maori_name %>
</p>
<p>
  <strong>English Name:</strong>
  <%=h @kind.english_name%>
</p>
<p>
	<%= @kind.description.html_safe %>
</p>
<p>
	<table>
		<tr>
			<td><%= image_tag @kind.get_icon.picture.image.url(:thumb) unless @kind.icon.blank? %> </td>
	</table>
</p>
<p>
  <%= link_to "Edit", edit_kind_path(@kind) %> |
  <%= link_to "Destroy", @kind, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", kinds_path %>
</p>