config/routes.rb
Treegeek::Application.routes.draw do
  
  resources :trees do
    resources :photos
    collection do
      get "search"
    end
  end

  resources :blogs

  
  resources :kinds do
    collection do
      get 'search'
    end
    member do
      get  'images'
    end
  end
  
  resources :pictures do
    member do
      put 'assignedtrees'
    end
    collection do
      post 'selected_trees'
      get 'search'
    end
  end
  
  
  resources :albums

  

end

app/models/tree.rb
class Tree

	include Mongoid::Document
	include Mongoid::Timestamps
	include Mongoid::Search

  	validate :kind_exists
  	validates_presence_of :location_desc

	field :location_desc
	field :given_name
	field :coord_lat
	field :coord_long
	field :date_planted, :type => Date
	# add who planted...but will require user model
	field :source

	embeds_many :dimensions
	referenced_in :kind

	search_in :given_name, :location_desc, :source, :kind => :botanic_name

	# returns any attribute (method) from the Kind class associated with this Tree; 
	# Note: also can use the references association instead of this.
	#
	# Supply a field will return only that field.
	# NOTE--Removed because the referenced_in is moved to this model.
	#def get_tree_kind_field(field)
		#Kind.only(field).where(:tree_id => self.id).first.send(field)
	#	@kind ||= Kind.where(:tree_id => self.id)
	#	@kind.first.send(field)
	#end


	# helper to add the kind reference and the dimensions embedding (called from controller)
	# a nil kind means that it wont be updated.
  def add_external_refs(params)
    #raise if kind_ref.nil?
    if params[:kind] != nil
      kind = Kind.find(params[:kind])
      kind.tree = self
      kind.save
    end
    unit = params[:unit]
    dim = params[:dimensions]
    self.dimensions.create(:height => {:value => dim[:hvalue], :unit => unit},
    :width => {:value => dim[:wvalue], :unit => unit},
    :observation => dim[:obs]) unless dim[:hvalue].empty? && dim[:wvalue].empty?
  end

  #remove all the external model references from the tree (those not managed by the MongoID deep delete
  def remove_references(options)
  	# just got to remove the assigned_pics Tree hash
  	Pictureandmeta.delete_event(self)
  end

  private

  def kind_exists
  	errors.add(:kind, "Must be added") if kind.nil?
  	#Rails.logger.info(">>>Validate kinds_exit>>>: #{kind.inspect}, #{errors.inspect}")
  end

end

app/controllers/trees_controller.rb
class TreesController < ApplicationController

  before_filter :check_authorisation, :with => :user_not_authorised
  before_filter :set_tree, :only => [:show, :edit, :update, :delete]

  def index
    @trees = Tree.all.page params[:page]
  end

  # GET /trees/new
  # path: new_tree_path
  def new
    @tree = Tree.new
  end

  # POST /trees
  def create
    #Rails.logger.info(">>>Tree Controller>>CREATE: #{params.inspect}")
    @tree = Tree.new(params[:tree])
    @tree.add_external_refs(params[:kind], params[:dimensions])
    if @tree.save
      flash[:notice] = "Successfully created tree."
      redirect_to @tree
    else
      render :action => 'new'
    end
  end

  # GET /trees/{id}
  def show
    #@tree = Tree.find(params[:id])
  end

  # GET /trees/edit
  def edit
    #@tree = Tree.find(params[:id])
  end

  # PUT /trees/{id}
  def update
    #@tree = Tree.find(params[:id])
    #
    #Rails.logger.info(">>>Update Tree: #{params.inspect} >> #{params[:dimensions]} >>> #{dim.inspect}")
    @tree.add_external_refs(params)
    respond_to do |format|
      if @tree.update_attributes(params[:tree])
        flash[:notice] = "Successfully updated tree."
        format.html {redirect_to @tree}
      else
        format.html { render :action => 'edit' }
      end
    end  
  end
  
  def destroy
     #
     # DELETE Tree
     #
     #@tree = Tree.find(params[:id])
     # remove references in other models
    @tree.remove_references(:scope => :all)
    respond_to do |format|
      if @tree.destroy
         flash[:notice] = "Successfully destroyed tree."
         format.html {redirect_to trees_url}
         format.js {render :nothing => true}
      else
        flash[:notice] = "Couldn't remove Tree"
        render :action => 'show'
      end
    end
   end

  # Collection Route methods here

    # This is basically an algorithm resource GET kinds/search
  def search
    # if the user has selected to clear the search, or there is no search params, start from the top
    if params[:clear] || params[:q] == ""
      redirect_to trees_path
    else  
      @trees = Tree.search(params[:q]).page params[:page]
      Rails.logger.info(">>>Tree Controller>>SEARCG: #{@trees.count}")
      render :index
    end
  end


  private

  def set_tree
    @tree = Tree.find(params[:id])
  end

  def check_authorisation
    # exception handling based on user authorisation
    # raise User::NotAuthorized unless current_user.admin?
  end

  def user_not_authorisated
    #flash[:error] = "You don't have access to this section." 
    #redirect_to :back
  end

end

app/helpers/trees_helper.rb
module TreesHelper
end

app/views/trees/_dimensions_show.html.erb
<p><strong>Dimension History</strong></p>
<table>
  <tr>
    <th>Date</th>
    <th>Height</th>
    <th>Width</th>
    <th>Observation</th>
  </tr>
  <% for dim in @tree.dimensions %>
    <tr>
      <td><%= dim.created_at %> </td>
      <td><%= "#{dim.height["value"]}#{dim.height["unit"]}" %></td>
      <td><%= "#{dim.width["value"]}#{dim.width["unit"]}" %></td>
      <td><%= dim.observation %> </td>
    </tr>
  <% end %>
</table>

app/views/trees/_form.html.erb
<%= form_for @tree do |f| %>
  <%= render "shared/error_messages", :target => @tree %>
  <p>
    <%= f.label :location_desc %><br />
    <%= f.text_field :location_desc %>
  </p>
  <p>
    <%= f.label :coord_lat %><br />
    <%= f.text_field :coord_lat %>
  </p>
  <p>
    <%= f.label :coord_long %><br />
    <%= f.text_field :coord_long %>
  </p>
<p>
    <%= f.label :date_planted %><br />
    <%= f.text_field :date_planted %>
  </p>
  <p>
    <%= f.label :given_name %><br />
    <%= f.text_field :given_name %>
  </p>
    <p>
    <%= f.label :source %><br />
    <%= f.text_field :source %>
    </p>

  <p>
      <%= f.label :kind %>
    <%= select_tag( :kind, options_for_select(Kind.all.map{|k| [k.botanic_name, k.id]})) %>
  </p>

	<%= render :partial => 'dimensions_show' %>

  <%= fields_for :dimensions do |dims| %>
    <div class="dimensions">
    <p>
    <%= dims.label :unit %>
    <%= select_tag :unit, options_for_select(["m", "ft", "cm"]) %>
    Height:
    <%= dims.text_field :hvalue %>
    Width:
    <%= dims.text_field :wvalue %>
    </p>
    <p>Observation</p>
    <p>
    <%= dims.label :obs %>
    <%= dims.text_field :obs %>
    </p>
    </div>

  <% end %>

  <p><%= f.submit "Submit" %></p>

<% end %>

app/views/trees/_form_old.html.erb
<%= form_for @tree do |f| %>
  <p>
    <%= f.label :location_desc %><br />
    <%= f.text_field :location_desc %>
  </p>
  <p>
    <%= f.label :coord_lat %><br />
    <%= f.text_field :coord_lat %>
  </p>
  <p>
    <%= f.label :coord_long %><br />
    <%= f.text_field :coord_long %>
  </p>
<p>
    <%= f.label :date_planted %><br />
    <%= f.text_field :date_planted %>
  </p>
  <p>
    <%= f.label :given_name %><br />
    <%= f.text_field :given_name %>
  </p>
    <p>
    <%= f.label :source %><br />
    <%= f.text_field :source %>
    </p>

  <p>
      <%= f.label :kind %>
    <%= select_tag( :kind, options_for_select(Kind.all.map{|k| [k.botanic_name, k.id]})) %>
  </p>

	<%= render :partial => 'dimensions_show' %>

  <%= fields_for :dimensions do |dims| %>
    <p>Height (provide the value and the unit (m|cm|ft))</p>
    <p>
    <%= dims.label :hvalue %>
    <%= dims.text_field :hvalue %>
    <%= dims.label :hunit %>
    <%= dims.text_field :hunit %>
    </p>
    <p>Width (provide the value and the unit (m|cm|ft))</p>
    <p>
    <%= dims.label :wvalue %>
    <%= dims.text_field :wvalue %>
    <%= dims.label :wunit %>
    <%= dims.text_field :wunit %>
    </p>
    <p>Observation</p>
    <p>
    <%= dims.label :obs %>
    <%= dims.text_field :obs %>
    </p>

  <% end %>

  <p><%= f.submit "Submit" %></p>

<% end %>

app/views/trees/_tree.html.erb
<div class="tree">
<div class="title">
	<% pm = Pictureandmeta.find_by_assigned_ref_with_id(tree, :result => :onerandom)%>
    <% if pm %>
	   <%= link_to image_tag(pm.picture.image.url(:thumb), :border => 0), 
										:action => 'edit', :controller => 'pictures', :id => pm.picture %>
    <% else %>
        No Image
    <% end %>
    <%= tree.given_name %> |
    <%= tree.kind.botanic_name %>
</div>
<div class="details">
    <%= tree.date_planted.to_s(:tree_date) %>
    <%= tree.location_desc %>
</div>
<div class="actions">
    <%= link_to "Show", tree %>
    <%= link_to "Edit", edit_tree_path(tree) %>
    <%= link_to "Destroy", tree, :confirm => 'Are you sure?', :method => :delete, :remote => true, :class => 'delete_tree' %>
</div>
<br/>
</div>

app/views/trees/edit.html.erb
<% title "Edit Tree" %>

<%= render :partial => 'form' %>

<p>
  <%= link_to "Show", @tree %> |
  <%= link_to "View All", trees_path %>
</p>

app/views/trees/index.html.erb
<% title "Trees" %>

<%= form_tag search_trees_path, :method => :get, :remote => true  do %>
  <p>
    <%= text_field_tag :q, params[:q]%>
    <%= submit_tag "Search", :name => nil %>
    <%= submit_tag "Clear", :name => "clear" %>
  </p>
<% end %>

<div id="tree_results">

	<div class="header">

  </div>
  <div id="trees">  
    <%= render @trees %>
	</div>


<%= paginate @trees %>

</div>

<p><%= link_to "New Tree", new_tree_path %></p>

app/views/trees/index.js.erb
$("#trees").html("<%= escape_javascript(render(@trees)) %>");

app/views/trees/new.html.erb
<% title "New Tree" %>

<%= render :partial => 'form' %>

<p><%= link_to "Back to List", trees_path %></p>

app/views/trees/show.html.erb
<% title "Tree List" %>

<%= render "shared/error_messages", :target => @tree %>

<% picture = @tree.kind.get_icon.picture %>
<p><%= link_to image_tag(picture.image.url(:thumb), :border => 0),
 							:action => 'edit', :controller => 'pictures', :id => picture %> </p>

<p>
  <strong>Location Description</strong>
  <%= @tree.location_desc %>
</p>
<p>
  <strong>Geo Location:</strong>
  Lat: <%= @tree.coord_lat %> Long: <%= @tree.coord_long %>
</p>
<p>
  <strong>Source</strong>
  <%= @tree.source%>
</p>
<p>
  <strong>Date Planted</strong>
  <%= @tree.date_planted.to_s(:tree_date)%>
</p>

<p>
  <strong>Given Name</strong>
  <%= @tree.given_name%>
</p>

<p>
  <strong>Botanic Name</strong>
  <%= @tree.kind.botanic_name %>
</p>

<%= render :partial => 'dimensions_show' %>

<% pm = Pictureandmeta.find_by_assigned_ref_with_id(@tree) %>

<% if pm %>
	<p><strong>Tree Pictures</strong>
		<table>
			<tr>
				<% for pictureandmeta in pm -%>
					<% picture = pictureandmeta.picture -%>
					<td><%= link_to image_tag(picture.image.url(:thumb), :border => 0), 
											:action => 'edit', :controller => 'pictures', :id => picture %></td>
					<td>Tags:
						<p><%= pictureandmeta.meta.tags %> </p>
						<p><%= link_to "remove", assignedtrees_picture_path(picture, :tree => @tree.id.to_s), :method => :put %></p>
					</td>
				<% end %>
			</tr>
		</table>
	</p>
<%end%>

<p>
	<div class="actions"
		<%= link_to "New Album", albums_path(:assigned_pics_tree => @tree.id.to_s) %>
		<%= link_to "New Picture", new_picture_path(:assigned_pics_tree => @tree.id.to_s)%>
		<%= link_to "Add Existing Picture", pictures_path(:assigned_pics_tree => @tree.id.to_s)%>
	</div>

</p>

<p>
  <%= link_to "Edit", edit_tree_path(@tree) %> |
  <%= link_to "Destroy", @tree, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", trees_path %>
</p>