config/routes.rb
Treegeek::Application.routes.draw do
  
  resources :trees do
    resources :photos
    collection do
      get "search"
    end
  end

  resources :blogs

  
  resources :kinds do
    collection do
      get 'search'
    end
    member do
      get  'images'
    end
  end
  
  resources :pictures do
    member do
      put 'assignedtrees'
    end
    collection do
      post 'selected_trees'
      get 'search'
    end
  end
  
  
  resources :albums

  

end

app/models/picture.rb
class Picture < ActiveRecord::Base
	
  validates_attachment_presence :image
  
  has_attached_file :image,
    :styles => {
      :thumb => "100x100>",
      :small => "150x150>",
      :medium => "300x300>" }
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  
  # The picture controller deals with the CRUD of images and their metadata.  These images can be anything, but are 
  # generally Tree images.
  
  
  def index
    # TODO Paging wont work because PictandMeta is not an ActiveModel
    @tree_id = params[:assigned_pics_tree].to_s if params[:assigned_pics_tree]
    @picturesandmeta = Pictureandmeta.all
  end
  
  def show
    @pictureandmeta = Pictureandmeta.find(params)
    #render :text => @picmeta.to_yaml
  end
  
  def new
    session[:assigned_pics_tree] = {:tree => [params[:assigned_pics_tree].to_s]} if params[:assigned_pics_tree]
    @pictureandmeta = Pictureandmeta.new
  end
  
  def edit
    @pictureandmeta = Pictureandmeta.find(params)
  end
  
  def update
    @pictureandmeta = Pictureandmeta.find(params)
    if @pictureandmeta.update(params)
      flash[:notice] = "Successfully updated Picture."
      redirect_to pictures_url
    else
      render :action => 'edit'
    end
  end
  
  def create
    params[:pictureandmeta][:picmeta][:assigned_pics] = session[:assigned_pics_tree] if session[:assigned_pics_tree]
    session[:assigned_pics_tree] = nil
    if Pictureandmeta.create(params)
      flash[:notice] = "Successfully created Picture."
      redirect_to pictures_url
    else
      flash[:notice] = "Error updating the Picture and or meta"
      render :action => 'new'
    end
  end
  
  def destroy
    @pictureandmeta = Pictureandmeta.find(params)
    if @pictureandmeta.destroy
      flash[:notice] = "Successfully destroyed picture."
      redirect_to pictures_url
    else 
      flash[:notice] = "Error in the delete"
      redirect_to pictures_url
     end
  end
  
  #  Collection resource methods here
  
  # gets involved from index when the user has requested to associate pictures with specific trees
  # uses a hidden field called selected_tree to hold the tree id.
  def selected_trees
    Rails.logger.info(">>>Selected Tree #{params.inspect}")
    if Pictureandmeta.add_assigned_pics(params['selected_tree'], params['add_to'])
      flash[:notice] = "Successfully added sslected pictures."
    else
      flash[:notice] = "Pictures not added due to error."
    end
    redirect_to :controller => 'trees', :action => 'show', :id => params['selected_tree']
  end
  

  # A PUT Resource that is called, currently, to remove a tree reference from a Picture.
  # IN: id of picture, id of tree
  def assignedtrees
    @pictureandmeta = Pictureandmeta.find(params)
    @pictureandmeta.delete_assigned_pics(params[:tree])
    redirect_to :controller => 'trees', :action => 'show', :id => params[:tree]
  end

  # This is basically an algorithm resource GET kinds/search
  def search
    # if the user has selected to clear the search, or there is no search params, start from the top
    Rails.logger.info("Pic Search: #{params.inspect}")
    if params[:clear] || params[:q] == ""
      redirect_to pictures_path
    else  
      @picturesandmeta = Pictureandmeta.search(params[:q])
      #@page = 1
      render :index
    end
  end



end

app/views/pictures/edit--tagversion.html.erb
<% title "Edit Picture" %>

<% picture = @pictureandmeta.picture -%>
<% meta = @pictureandmeta.meta -%>

<% form_tag :action => :update, :id => picture, :html => { :method => :put, :multipart => true } do %>

		<p>
			<label for="name">Picture Name:</label>
			<%= text_field_tag :name, meta.name %>
		</p>
		
		<p>
			<label for="description">Description:</label>
			<%= text_area_tag :description, meta.description, :cols => 40, :rows => 5 %>
		</p>
		<p>
			<label for="date_taken">Date Taken:</label>
			<%= text_field_tag :date_taken, meta.date_taken %>
		</p>
		<p>	
			<label for="photographer">Photographer:</label>
			<%= text_field_tag :photographer, meta.photographer %>
		</p>
	<p>
		<%= image_tag picture.image.url(:medium) %>
		
		<% fields_for picture do |f| %>
		  	<%= f.label :image%> <br/>
			<%= f.file_field :image%>
		<% end %>
		
	</p>
	


  <%= submit_tag "Submit" %>
  
<% end %>

app/views/pictures/edit.html.erb
<% title "Edit Picture" %>

<% picture = @pictureandmeta.picture -%>
<% picmeta = @pictureandmeta.meta -%>

<%= form_for :pictureandmeta, :url => picture_path, :html => { :method => :put, :multipart => true } do |form| %>

	<%= form.fields_for picmeta do |f| -%>
		<p>			
			<%= f.label "Picture Name" %><br />
			<%= f.text_field :name %>
		</p>
		
		<p>
			<%= f.label :description %><br />
			<%= f.text_area :description, :cols => 40, :rows => 5 %>
		</p>
		<p>
			<%= f.label :date_taken %><br />
			<%= f.text_field :date_taken %>
		</p>
		<p>	
			<%= f.label :photographer %><br />
			<%= f.text_field :photographer %>
		</p>
		<p>	
			<%= f.label :tags %><br />
			<%= f.text_field(:tags, :value => picmeta.tags) %>
		</p>


	<% end %>
	<p>
		<%= image_tag picture.image.url(:medium) %>
		
		<% if !picture %>
			<%= form.fields_for picture do |f| %>
				<p>
				  	<%= f.label :image%> <br/>
					<%= f.file_field :image %>
				</p>
			<% end %>
		<% end %>
	</p>
	
  <%= form.submit "Submit" %>
  
<% end %>

app/views/pictures/index--old.html.erb
<% title "Pictures" %>

<table>
	<tr>
		<th>
			Picture Name
		</th>
		<th>
			Picture
		</th>
	</tr>
	<% for picture in @pictures -%>
		<% ref = @picmetas.select {|pm| pm.ext_picture_id == picture.id.to_s} -%>
		<% r = ref[0] -%>
			<tr>
				<td><%=h r.name %></td>
				<td><%= image_tag picture.image.url(:thumb)%>
	      		<td><%= link_to "Show", picture %></td>
	      		<td><%= link_to "Edit", edit_picture_path(picture) %></td>
	      		<td><%= link_to "Destroy", picture, :confirm => 'Are you sure?', :method => :delete %></td>
			</tr>
  	<% end -%>
</table>

<p><%= link_to "New Picture", new_picture_path %></p>

app/views/pictures/index.html.erb
<% title "Pictures" %>

<%= form_tag search_pictures_path, :method => :get do %>
  <p>
    <%= text_field_tag :q, params[:q] %>
    <%= submit_tag "Search", :name => "search" %>
    <%= submit_tag "Clear", :name => "clear" %>
  </p>
<% end %>

<table>
	<tr>
		<th>
			Picture Name
		</th>
		<th>
			Picture
		</th>
		<% if @tree_id %>
			<th>Select Picture for Tree</th>
		<% end %>
	</tr>		
	<% if @tree_id %>
		<%= form_tag selected_trees_pictures_path do  %>
			<% for pictureandmeta in @picturesandmeta -%>
				<% picture = pictureandmeta.picture %>
				<tr>
					<td><%=h pictureandmeta.meta.name %></td>
					<td><%= link_to image_tag(picture.image.url(:thumb), :alt => "show #{pictureandmeta.meta.name}", :border => 0), 
															:action => 'show', :id => picture %>
					<% if pictureandmeta.meta.assignedrefs.where(:ref => @tree_id).exists? %>
						<td>Already Selected</td>
					<% else %>
						<td><%= check_box_tag "add_to[]", picture.id %></td>
					<% end %>
				</tr>
			<% end %>
			</table>
			<%= hidden_field_tag "selected_tree", @tree_id %>
			<%= submit_tag "Assign", :name => nil %>
		<% end %>
	<% else %>
		<% for pictureandmeta in @picturesandmeta -%>
			<% picture = pictureandmeta.picture -%>
			<tr>
				<td><%=h pictureandmeta.meta.name %></td>
				<td><%= link_to image_tag(picture.image.url(:thumb), :alt => "show #{pictureandmeta.meta.name}", :border => 0), 
																:action => 'show', :id => picture %>
				<td><%= link_to "Show", picture, :class => "stdbutton2" %></td>				
				<td><div class="stdbutton2"><%= link_to "edit", edit_picture_path(picture) %><div></td>
				<td><%= link_to "delete", picture, :confirm => 'Are you sure?', :method => :delete, :class => "stdbutton2" %></td>
			</tr>
		<% end %>
		
	<% end %>
</table>


<p><%= link_to "New Picture", new_picture_path, :class => "stdbutton" %>
</p>

app/views/pictures/new.html.erb
<% title "Picture" %>

<% picture = @pictureandmeta.picture -%>
<% picmeta = @pictureandmeta.meta -%>

<%= "Session: #{session[:assigned_pics_tree]}" %>

<%= form_for :pictureandmeta, :url => pictures_path, :html => { :multipart => true } do |form| %>

	<%= form.fields_for :picmeta do |f| %>
		<p>
			
			<%= f.label :name %><br />
			<%= f.text_field :name %>
		</p>
		
		<p>
			<%= f.label :description %><br />
			<%= f.text_area :description, :cols => 40, :rows => 5 %>
		</p>
		<p>
			<%= f.label :date_taken %><br />
			<%= f.text_field :date_taken %>
		</p>
		<p>	
			<%= f.label :photographer %><br />
			<%= f.text_field :photographer %>
		</p>
		<p>	
			<%= f.label :tags %><br />
			<%= f.text_field :tags %>
		</p>

	<% end %>
	<p>
		<%= form.fields_for :picture do |f| %>
		  	<%= f.label :image%> <br/>
			<%= f.file_field :image%>
		<% end %>
	</p>
	


  <%= form.submit "Create" %>
  
<% end %>

app/views/pictures/show.html.erb
<% title "Picture", @pictureandmeta.meta.name %>

<% picture = @pictureandmeta.picture -%>

<p>
  <strong>Name:</strong>
  <%=h @pictureandmeta.meta.name %>
</p>
<p>
  <strong>Description</strong>
  <%=h @pictureandmeta.meta.description.html_safe %>
</p>
<p>
  <strong>Date</strong>
  <%=h @pictureandmeta.meta.date_taken%>
</p>
<p>
	<strong>Photographer</strong>
	<%=h @pictureandmeta.meta.photographer%>
</p>
<p>
	<%= image_tag picture.image.url(:medium) %> </br>
		Tags:
	<%= @pictureandmeta.meta.tags %>
</p>
<p>
  <%= link_to "Edit", edit_picture_path(picture) %> |
  <%= link_to "Destroy", picture, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", pictures_path %>
</p>	
	