config/routes.rb
Treegeek::Application.routes.draw do
  
  resources :trees do
    resources :photos
    collection do
      get "search"
    end
  end

  resources :blogs

  
  resources :kinds do
    collection do
      get 'search'
    end
    member do
      get  'images'
    end
  end
  
  resources :pictures do
    member do
      put 'assignedtrees'
    end
    collection do
      post 'selected_trees'
      get 'search'
    end
  end
  
  
  resources :albums

  

end

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end
  
  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title><%= content_for?(:title) ? content_for(:title) : 'TreeGeek' %></title>
    <%= yield(:head) %>

  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
  <%= include_tiny_mce_if_needed %>
</head>
  <body>
	<div id="container">
		
		<div id="header">
			<h1><%= content_for?(:header_title) ? content_for(:header_title) : 'TreeGeek' %></h1>
		</div>	
    	<div id="content">
      		<%- flash.each do |name, msg| -%>
        		<%= content_tag :div, msg, :id => "flash_#{name}" %>
      		<%- end -%>      
      		<%= yield %>
    	</div>
		<div id="sidebar">
			<table>
				<tr>
        			<td><%= link_to "Trees", trees_path %> </td>
      			</tr>
      			<tr>
					<td><%= link_to "Tree Kinds", kinds_path %></td>
				</tr>
					<tr><td><%= link_to "All Pictures", pictures_path %></td>
				</tr>
			</table>
		</div>
	</div>
  </body>
</html>